### ISSUE TITLE
Commands for chance and global chance

### ISSUE THREAD

**Issue by NoraCodes** [alekratz/markov-bot#1]
Perhaps commands could be added to set the chance of the bot triggering on a specific user's messages, like !markov chance <percentage> or to set the global chance?

**Comment by alekratz** [comment]
[Global chance already exists](https://github.com/alekratz/markov-bot/blob/9d9b93b549bf95f599532a43856206f2fe2ae9c2/src/main/kotlin/edu/appstate/cs/markovbot/Main.kt#L52), it's just not documented yet. I haven't thought about allowing users to set their random chance; but if I were to do that, I'd only allow them to set their chance to between 0.0 and the global setting to avoid abuse.

**Comment by alekratz** [comment]
Alright, so I've put some thought in to this and I think it's a good idea for a feature. It's on the wishlist, and if someone feels like implementing this, they're welcome to.
